name: Continuous Integration

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: |
          rustup update
          rustup component add rustfmt
          rustup component add clippy

      - name: Run build
        run: cargo build

      - name: Run tests
        run: cargo test

      - name: Run formatting and linting
        run: |
          cargo fmt --check
          cargo clippy -- -D warnings

  publish:
    name: Publish
    if: ${{ github.ref_type == 'tag' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        run: rustup update

      - name: Login to crates.io
        run: cargo login ${{ secrets.CRATES_TOKEN }}

      - name: Publish to crates.io
        run: cargo publish
